AWSTemplateFormatVersion: "2010-09-09"
Description: ECR repository for hf-ml-platform rate limiter

Resources:
  RateLimiterRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: hf-ml-platform/rate-limiter
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": { "type": "expire" }
              }
            ]
          }

Outputs:
  RepositoryUri:
    Value: !GetAtt RateLimiterRepo.RepositoryUri
    Export:
      Name: HfMlPlatformRateLimiterRepositoryUri
